"""
Lesson 1: Python Basics from Crash Course by Eric Matthes 
Chapter 2

Topics:
- Variables
- Strings \t \n and f-strings 
- String manipulation .title(), .upper(), .lower() .strip(), .rstrip(), .lstrip() 
- Avoiding syntax errors
- The Zen of Python

Remarks: 
some of the comments are generated by copilot and modified by me; others are written entirely by me.

Use of def main() and if __name__ == "__main__":
- It helps to organize the code and makes it easier to read and maintain. It makes the code testable, importable and scalbale. 
"""
def main():
    print("Hello World!") 

    # --- Variables and Strings ---
    wrong_case_string = "i love you"
    print(wrong_case_string.title()) 
    print(wrong_case_string.upper()) 
    print(wrong_case_string.lower()) 

    # --- Using f-Strings to Combine Strings ---
    first_name = "python"
    last_name = "green"
    full_name = f"{first_name} {last_name}"
    print(first_name + " " + last_name)
    print(full_name) # Using f-Strings to Combine Strings
    print(f"Hello, {full_name.title()}!") # Using f-Strings to Combine Strings
    message = f"Hello, {full_name.title()}!"
    print(message) # Using f-Strings to Combine Strings

    # --- Stripping Whitespace ---
    favourite_language = " python      "
    print(f"Hej, {favourite_language.title()} is my favourite language!") 
    print(f"Hej, {favourite_language.rstrip().title()} is my favourite language! with .rstrip()")
    print(f"Hej, {favourite_language.lstrip().title()} is my favourite language! with .lstrip()")
    print(f"Hej, {favourite_language.strip().title()} is my favourite language! with .strip()") 
    print(f"Hej, {favourite_language.title()} is my favourite language! \n\tBut .rstrip() does not remove the trailing whitespace permanently.") 

    # --- Avoiding Syntax Errors with Strings ---
    name = "\ttIM peTERS \n"
    message = "Beautiful is better than ugly."
    print(f"{name} above contains \\t a tab in the beginning and \\n a new line") # Avoiding Syntax Errors with Strings
    print(f"\nThe Zen of Python, by {name.title().strip()} \n\"{message}\" \n above uses name.title().strip() and {r'\"'} ") # Avoiding Syntax Errors with Strings 
    # r'' creates a raw string, so backslashes are not treated as escape characters

    # --- The Zen of Python ---
    import this

if __name__ == "__main__":
    main()